<?php
					/* Events */
	$events = array('Z1'=>'state_entry()',
					'Z2'=>'on_rez(integer num)',
					'Z3'=>'touch_start(integer num)',
					'Z4'=>'collision_start(itenger num)',
					'Z5'=>'listen(integer channel, string name, key id, string message)',
					'Z6'=>'timer()' );
		
	$functions = array(	/* Communication */
					'A1'=>'llSay([0],"[1]");',
					'A2'=>'llShout([0],"[1]");',
					'A3'=>'llWhisper([0],"[1]");',
					'A4'=>'llRegionSay([0],"[1]");',
					'A5'=>'llOwnerSay("[0]");',
					/* Movement ( [3] = 'llGetPos() +' )*/
					'B1'=>'llSetPos(<[0],[1],[2]>);',
					'B2'=>'llMoveToTarget([3]<[0],[1],[2]>);',
					'B3'=>'llLookAt(<[0],[1],[2]>);',
					'B4'=>'llSetRot(llGetRot());', //IMPLEMENTAR DEG TO RAG
					/* Style */
					'C1'=>'llSetColor(<[0]>,[2]);',
					'C2'=>'llSetTexture("[0]",[1]);',
					'C3'=>'llSetAlpha([0],[1]);',
					/* Misc */
					'D1'=>'llSetText([0],<[1]>,[2]);',
					'D2'=>'llGiveInventory([1],[0]);',
					'D3'=>'llLoadURL([2],[0],[1]);',
					'D4'=>'llPlaySound([0],[1]);',
					/* Helper */
					'E1'=>'if([0])',
					'E2'=>'llSleep([0]);',
					'E3'=>'llDie();',
					'E4'=>'llSetTimerEvent([0]);',
					/* Coments */
					'CC'=>'//[0]'
				);
		
					/* GLOBAL */
		$global = array(
					'LOCAL_POS'=>'> + llGetPos()',
					'SET_PHYSIC'=>'if( !(llGetStatus() && STATUS_PHYSICS) ) {	llSetStatus(STATUS_PHYSICS,TRUE);	}',
					'DEL_PHYSIC'=>'llSetStatus(STATUS_PHYSICS,FALSE);',
					'AT_TARGET'=>'at_target(integer tnum, vector targetpos, vector ourpos)',
					'VAR_TARGET'=>'integer target;',
					'SET_TARGET'=>'target = llTarget([3]<[0],[1],[2]>,1);',
					'DEL_TARGET'=>'llTargetRemove(target);'					
				);
	
	$action = $_POST['action'];
	
	if($action == 'build') {
		$_code = $_POST['code'];
		$_comm = $_POST['comments'];
		// EVENTO:
		//	FUNCION% b64(CONTENIDO) | b64(CONTENIDO)
		// ,
		
		//Z1:A1%MA==|c3RhcnQ=/A1%MA==|c3RhcnQ=,Z2:A1%MA==|cmV6
		$EVENTOS = explode(',',$_code);
		
		//Abrir script
		$Script .= '// Generated by devi LSLGen v0.1-alpha<br/><br/>';
		$Script .= '// Create your own script at: http://foravatars.com/sandbox/lsl<br/>';
		$Script .= '<br/><br/>'; // Para agregar datos arriba del defaul;
		$Script .= 'default		{<br/>';
		
		foreach($EVENTOS as $evento) {
			$eData = explode(':',$evento);
			
			$TituloEvento = $eData[0];
			$ContenidoEvento = $eData[1];
			
			$aFunciones = explode('/',$ContenidoEvento);
			
			// Abrir evento
			$Script .= '<blockquote>'.$events[$TituloEvento]. ' {<br/>';
			
			foreach($aFunciones as $funcion) {
				$fData = explode('%',$funcion);
				
				$TituloFuncion = $fData[0];
				
				$ContenidoFuncion = explode('|',$fData[1]);
				$ValoresFuncion = array();
				
				$i = 0; // Guardar los valores de esta función
				foreach($ContenidoFuncion as $valor) {
					$valor = urldecode(base64_decode($valor));
					$ValoresFuncion[$i] = $valor;
					$i++;
				}
				
				$Funcion = $functions[$TituloFuncion];
				
				//Procesar función:
				foreach($ValoresFuncion as $i=>$val) {
					if($ValoresFuncion[$i+1] == 'on') {
						//$fun = $TituloFuncion; //substr($TituloFuncion,0,0);
						if($TituloFuncion[0] == 'B') {// Es true para pos local
							$add = '>';
							$val = $val .$global['LOCAL_POS'];
						} if($TituloFuncion[0] == 'C') { //Es true para ALL_SIDES
							$val = 'ALL_SIDES';
						} //echo 'on_true->'.$val.'->'.$TituloFuncion[0];
					} 
					//Verificar para Fly to ya que necesita extra
					//Verificar IF...
					$Funcion = str_replace('['.$i.']'.$add,$val,$Funcion);					
				}
				
				$Script.= '<blockquote style="margin-top:0;margin-bottom:0">'.$Funcion.'</blockquote>';
			}
			
			$Script .= '}</blockquote>';
			// Cerrar evento
		}
		
		$Script .= '}';
		//REMOVER [OVER_DEFAUL]
		// Cerrar script		
		echo $Script;
		//logScript($Script, $_code);
	}
	
	function logScript($result, $code) {
		$file_name = 'log_'.date('Ymd-gia').'.txt';
		$fh = fopen('log/'.$file_name, 'w+') or die("can't open file");
		$stringData = str_replace(array('<br/>','<blockquote>','</blockquote>'),array('\n','	',''),$result).'\n\n\n'.$code;
		fwrite($fh, $stringData);
		fclose($fh);
	}